# docker-compose.yml
version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins_server
    volumes:
      - jenkins_home:/var/jenkins_home
    links:
      - docker

  docker:
    image: docker:dind
    privileged: true
    container_name: dind_daemon

volumes:
  jenkins_home:
